= SPA 2016 Session - Naked Objects: 14 Years On

This repository holds the tutorial slides for the
link:http://www.spaconference.org/spa2016/sessions/session677.html[Naked Objects: 14 Years On] session, run at
link:http://spaconference.org/spa2016/[SPA 2016] on 28th Jun 2016.


Being run by link:http://www.spaconference.org/scripts/people.php?username=DanHaywood[Dan Haywood], with more than
a little help from Jeroen van der Wal.


== Abstract

Back in 2002, when this conference went by the name OT (Object Technology), there was a Sunday afternoon session that
changed my career forever.  That session was called "Naked Objects", and was presented by Richard Pawson and Rob
Matthews, who introduced their newly-developed (and to be frank, rather raw) Naked Objects Framework for Java.  You
can read my bio as to what happened after that; abbreviated version, I now work almost exclusively developing naked
objects apps, and it's a great fun.

So this session is an opportunity for you to get started with http://isis.apache.org/[Apache Isis], the platform that
the original framework has grown into.  The objective will be to develop a small application of a handful of domain
objects, but also to get to grips with Isis' support for business- and developer-level tests, how the framework
encourages modularity (through mixins and events), can be used as a REST backend for custom mobile apps.  You'll
also learn about and integrate some of the various addons available (security, auditing, profiling etc).

At the end of the session you should have a good understanding of the types of apps that the framework can be used to
build; and you never know, your career might end up changing forever too!




== Audience Background

Technically, you'll need to be ok with Java, Maven and an IDE (IntelliJ or Eclipse or NetBeans).  You'll also need to
have reasonably good modelling/design skills.  If you have only one or the other, bring a chum to pair with.


== Benefits of Participating

* Learn how to use the Apache Isis framework:
  - for prototyping (eg to elicit reqts/explore domain with business)
  - for line-of-business enterprise apps
  - for backend REST APIs (eg for mobile apps, microservices)
* Determine whether this framework fits your own use cases


== Materials

We'll provide a set of examples and tutorials learn the framework's conventions, and we'll provide guidance and structure to get attendees to build their own app.


== Structure

In the original OT2002 session the exercises were done teams of 4 or so; however working in pairs would possibly work
better.  My thoughts are that the first 1/3 would be in running through tutorials singly or in pairs; then to have the
attendees brainstorm some ideas for apps to build; then to pair off for the rest of the session to go ahead and
actually build those apps.  The last 20 minutes would be a wrap-up to summarize what had been learnt and identify
next steps, if any.


== Timetable

* `00:00-00:20` intro
* `00:20-01:20` tutorials
* `01:20-01:30` brainstorming, break
* `01:30-03:10` working on own apps
* `03:10-03:30` wrap-up


== Tutorial

The tutorial slides can be found at: link:http://danhaywood.github.io/spa2016[danhaywood.github.io/spa2016].  Open up
the slides and then navigate around and explore.


== Under the covers

The tutorial slides have been developed using link:http://asciidoctor.org/[AsciiDoctor], using
link:http://lab.hakim.se/reveal-js/[reveal.js] as the rendering backend.  Why?  Well, because the Apache Isis
documentation is all written using AsciiDoctor, and I wanted to learn how to write presentations using the approach
also.

== To build and preview

To build and preview the website, use:

[source,bash]
----
$ sh preview.sh
----

or in long-hand:

[source,bash]
----
./gradlew clean asciidoctor && cd build/asciidoc/revealjs && python -m SimpleHTTPServer 8000
----

Then open link:http://localhost:8000/index.html[http://localhost:8000/index.html]



== To publish

The tutorial is hosted at link:http://danhaywood.github.io/spa2016[danhaywood.github.io/spa2016], using github's
`gh-pages`.

Assuming that a second copy of the repository is checked out to `../spa2016-gh-pages`, in the `gh-pages` branch, use:

[source,bash]
----
sh publish.sh
----

or in long-hand:

[source,bash]
----
pushd ../spa2016-gh-pages
git rm -rf .
popd
pushd build/asciidoc/revealjs
cp -r . ../../../../spa2016-gh-pages/.
popd
pushd ../spa2016-gh-pages
git add .
git commit -m "updating"
git push origin gh-pages
popd
----




== Appendices

=== Preparing the `gh-pages` branch

Using the procedure described https://help.github.com/articles/creating-project-pages-manually/[here], the
following steps were performed to set up the `gh-pages` branch for publishing:

[source,bash]
----
git clone https://github.com/danhaywood/spa2016.git ../spa2016-gh-pages
cd ../spa2016-gh-pages
git checkout --orphan gh-pages
git rm -rf .
rm '.gitignore'
echo "My Page" > index.html
git add index.html
git commit -a -m "First pages commit"
git push origin gh-pages
----


=== IntelliJ

If you're using IntelliJ you can generate the IDE's files via:

 $ ./gradlew idea

Open the file _build/asciidoc/reveal/example-manual.html_ in your browser to see the generated revealjs file.
